apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: grafana-foundation-sdk
  title: Grafana Foundation SDK
  annotations:
    github.com/project-slug: grafana/grafana-foundation-sdk
  tags:
    - gitops
  links:
    - title: "Internal Slack Channel #app-platform"
      url: https://grafanalabs.enterprise.slack.com/archives/C04RVCAG9B5
  description: |
    Set of tools, types and libraries for building and manipulating Grafana objects.
spec:
  type: library
  owner: group:default/grafana-app-platform-squad
  lifecycle: experimental
