name: Missing fields
description: Report a missing field/builder in any model.
title: "[Schemas]: Missing <field> field for <model>"

body:
  - type: markdown
    attributes:
      value: |
        Code generated is based on schemas and they could miss some fields.
  - type: markdown
    attributes:
      value: |
        #

  - type: dropdown
    id: version
    attributes:
      label: version
      description: What's version are you using?
      options:
        - 11.3.x
        - 11.2.x
        - 11.1.x
        - 11.0.x
        - 10.4.x
        - 10.3.x
        - 10.2.x
        - 10.1.x
      default: 0
    validations:
      required: true

  - type: input
    id: schema
    attributes:
      label: Missing field.
      description: In which model is the field missing?
      placeholder: "Example: Missing abc field in Dashboard"
    validations:
      required: true

  - type: input
    id: documentation
    attributes:
      label: Link to documentation.
      description: Link the documentation where is the field defined.
      placeholder: "Example: https://grafana.com/docs/grafana/latest/dashboards/build-dashboards/view-dashboard-json-model/#panel-size-and-position"

  - type: textarea
    attributes:
      label: Do you want to add any other information?

