name: TypeScript Release
on:
  push:
    branches:
      - '{{ .Extra.ReleaseBranch|replace "+" "\\+" }}'

env:
  NODE_VERSION: '18'

jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    defaults:
      run:
        shell: bash
        working-directory: ./typescript

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js {{ `${{ env.NODE_VERSION }}` }}
        uses: actions/setup-node@v4
        with:
          node-version: {{ `${{ env.NODE_VERSION }}` }}
          scope: '@grafana'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build
        
      - name: Get secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@75804962c1ba608148988c1e2dc35fbb0ee21746
        with:
          repo_secrets: |
            NPM_TOKEN=secrets:npm_token

      - name: Publish to NPM registry
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: {{ `${{ env.NPM_TOKEN }}` }}
