name: "Setup cog"
description: "Downloads cog and adds it to the $PATH"
inputs:
  version:
    description: "Cog version to install"
    required: true
    default: "0.0.17"
runs:
  using: "composite"
  steps:
    - name: Download cog
      shell: bash
      run: |
        mkdir -p "${HOME}/.local/bin/"
        wget https://github.com/grafana/cog/releases/download/v${{ inputs.version }}/cog_Linux_x86_64.tar.gz
        tar -xzf cog_Linux_x86_64.tar.gz
        mv cog "${HOME}/.local/bin/cog"
        chmod +x "${HOME}/.local/bin/cog"
        echo "${HOME}/.local/bin" >> $GITHUB_PATH
