// Code generated - EDITING IS FUTILE. DO NOT EDIT.

import * as cog from '../cog';
import * as dashboard from '../dashboard';

// Row panel
export class RowBuilder implements cog.Builder<dashboard.RowPanel> {
    protected readonly internal: dashboard.RowPanel;

    constructor(title: string) {
        this.internal = dashboard.defaultRowPanel();
        this.internal.type = "row";
        this.internal.title = title;
    }

    /**
     * Builds the object.
     */
    build(): dashboard.RowPanel {
        return this.internal;
    }

    // Whether this row should be collapsed or not.
    collapsed(collapsed: boolean): this {
        this.internal.collapsed = collapsed;
        return this;
    }

    // Row title
    title(title: string): this {
        this.internal.title = title;
        return this;
    }

    // Name of default datasource for the row
    datasource(datasource: dashboard.DataSourceRef): this {
        this.internal.datasource = datasource;
        return this;
    }

    // Row grid position
    gridPos(gridPos: dashboard.GridPos): this {
        this.internal.gridPos = gridPos;
        return this;
    }

    // Unique identifier of the panel. Generated by Grafana when creating a new panel. It must be unique within a dashboard, but not globally.
    id(id: number): this {
        this.internal.id = id;
        return this;
    }

    // List of panels in the row
    withPanel(panel: cog.Builder<dashboard.Panel>): this {
        if (!this.internal.panels) {
            this.internal.panels = [];
        }
        const panelResource = panel.build();
        this.internal.panels.push(panelResource);
        return this;
    }

    // Name of template variable to repeat for.
    repeat(repeat: string): this {
        this.internal.repeat = repeat;
        return this;
    }
}
