name: Python Release
on:
  push:
    tags: ["v*"]

env:
  PYTHON_VERSION: '3.12'

jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  # mandatory for trusted publishing

    environment:
      name: pypi
      url: https://pypi.org/p/grafana_foundation_sdk

    defaults:
      run:
        shell: bash
        working-directory: ./python

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install pypa/build@54f238d1664124e06a68c6c22fd5b1418fa5feb2 #v1.4.0
        run: python3 -m pip install build --user

      - name: Build a binary wheel and a source tarball
        run: python3 -m build

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with:
          packages-dir: python/dist/
          attestations: false
