name: Java Release
on:
  push:
    branches:
      - '{{ .Extra.ReleaseBranch|replace "+" "\\+" }}'

env:
  JAVA_VERSION: '17'

jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest

    permissions:
      contents: read

    defaults:
      run:
        shell: bash
        working-directory: ./java

    steps:
      - uses: actions/checkout@v4

      - name: Uses Java SDK {{ `${{ env.JAVA_VERSION }}` }}
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 #v4.7.1
        with:
          java-version: {{ `${{ env.JAVA_VERSION }}` }}
          distribution: 'temurin'
          check-latest: true

      - name: Java setup gradle
        uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 #v4.3.1
        with:
          gradle-version: '8.8'
          
      - name: Publish package 📦
        env:
          OSSRH_USERNAME: {{ `${{ secrets.OSSRH_USERNAME }}` }}
          OSSRH_PASSWORD: {{ `${{ secrets.OSSRH_PASSWORD }}` }}
          SIGNING_KEY: {{ `${{ secrets.SIGNING_KEY }}` }}
          SIGNING_PASSWORD: {{ `${{ secrets.SIGNING_PASSWORD }}` }}
        run:
          gradle publishToSonatype closeAndReleaseSonatypeStagingRepository
  
